/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_main;

import Hieu_ung.Hieuung;
import Contructor.danhmuc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;



/**
 *
 * @author haloi
 */
public class Form_Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Form_Main
     */
    public Form_Main() {
        initComponents();
        Hieuung hieu_ung = new Hieuung(jPanel_view);
        hieu_ung.setView(jPanel_docgia, quanly_docgia);
        List<danhmuc> list = new ArrayList<>();
        list.add(new danhmuc("quan_ly_doc_gia", jPanel_docgia, quanly_docgia));
        list.add(new danhmuc("quan_ly_sach", jPanel_sach, quanlysach));
        list.add(new danhmuc("quan_ly_muon_tra", jPanel_muontra, quanly_muontra));
        list.add(new danhmuc("quan_ly_nhap_sach", jPanel_nhap, quanly_nhap));
        list.add(new danhmuc("thong_ke", jPanel_thongke, thongke));
        list.add(new danhmuc("quan_ly_nguoi_dung", jPanel_nguoidung, quanly_nguoidung));
        hieu_ung.seteVent(list);
        
    }
    public JPanel getjpanel_nguoi_dung(){
        return jPanel_nguoidung;
    }    
    public JLabel getjlabel_nguoi_dung(){
        return quanly_nguoidung;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Frame = new javax.swing.JPanel();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_logo = new javax.swing.JLabel();
        jPanel_docgia = new javax.swing.JPanel();
        quanly_docgia = new javax.swing.JLabel();
        jPanel_nguoidung = new javax.swing.JPanel();
        quanly_nguoidung = new javax.swing.JLabel();
        jPanel_thongke = new javax.swing.JPanel();
        thongke = new javax.swing.JLabel();
        jPanel_muontra = new javax.swing.JPanel();
        quanly_muontra = new javax.swing.JLabel();
        jPanel_sach = new javax.swing.JPanel();
        quanlysach = new javax.swing.JLabel();
        close_form = new javax.swing.JLabel();
        jPanel_nhap = new javax.swing.JPanel();
        quanly_nhap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_view = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý thư viện");
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel_Frame.setBackground(new java.awt.Color(204, 255, 204));
        jPanel_Frame.setPreferredSize(new java.awt.Dimension(1280, 700));

        jPanel_menu.setBackground(new java.awt.Color(217, 235, 255));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(204, 700));

        jLabel_logo.setBackground(new java.awt.Color(217, 235, 255));
        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/image.png"))); // NOI18N

        jPanel_docgia.setBackground(new java.awt.Color(217, 235, 255));

        quanly_docgia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanly_docgia.setText("Quản lý độc giả");
        quanly_docgia.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 0));

        javax.swing.GroupLayout jPanel_docgiaLayout = new javax.swing.GroupLayout(jPanel_docgia);
        jPanel_docgia.setLayout(jPanel_docgiaLayout);
        jPanel_docgiaLayout.setHorizontalGroup(
            jPanel_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_docgiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quanly_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_docgiaLayout.setVerticalGroup(
            jPanel_docgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_docgiaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quanly_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_nguoidung.setBackground(new java.awt.Color(217, 235, 255));

        quanly_nguoidung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanly_nguoidung.setText("Quản lý người dùng");

        javax.swing.GroupLayout jPanel_nguoidungLayout = new javax.swing.GroupLayout(jPanel_nguoidung);
        jPanel_nguoidung.setLayout(jPanel_nguoidungLayout);
        jPanel_nguoidungLayout.setHorizontalGroup(
            jPanel_nguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nguoidungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quanly_nguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_nguoidungLayout.setVerticalGroup(
            jPanel_nguoidungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nguoidungLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quanly_nguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel_thongke.setBackground(new java.awt.Color(217, 235, 255));

        thongke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thongke.setText("Thống kê");

        javax.swing.GroupLayout jPanel_thongkeLayout = new javax.swing.GroupLayout(jPanel_thongke);
        jPanel_thongke.setLayout(jPanel_thongkeLayout);
        jPanel_thongkeLayout.setHorizontalGroup(
            jPanel_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_thongkeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_thongkeLayout.setVerticalGroup(
            jPanel_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_thongkeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(thongke, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel_muontra.setBackground(new java.awt.Color(217, 235, 255));

        quanly_muontra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanly_muontra.setText("Quản lý mượn trả");

        javax.swing.GroupLayout jPanel_muontraLayout = new javax.swing.GroupLayout(jPanel_muontra);
        jPanel_muontra.setLayout(jPanel_muontraLayout);
        jPanel_muontraLayout.setHorizontalGroup(
            jPanel_muontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_muontraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quanly_muontra, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_muontraLayout.setVerticalGroup(
            jPanel_muontraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_muontraLayout.createSequentialGroup()
                .addComponent(quanly_muontra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_sach.setBackground(new java.awt.Color(217, 235, 255));

        quanlysach.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanlysach.setText("Quản lý sách");

        javax.swing.GroupLayout jPanel_sachLayout = new javax.swing.GroupLayout(jPanel_sach);
        jPanel_sach.setLayout(jPanel_sachLayout);
        jPanel_sachLayout.setHorizontalGroup(
            jPanel_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quanlysach, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_sachLayout.setVerticalGroup(
            jPanel_sachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_sachLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quanlysach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        close_form.setBackground(new java.awt.Color(255, 255, 255));
        close_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-35.png"))); // NOI18N
        close_form.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_formMouseClicked(evt);
            }
        });

        jPanel_nhap.setBackground(new java.awt.Color(217, 235, 255));
        jPanel_nhap.setPreferredSize(new java.awt.Dimension(210, 52));

        quanly_nhap.setBackground(new java.awt.Color(217, 235, 255));
        quanly_nhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quanly_nhap.setText("Quản lý nhập");

        javax.swing.GroupLayout jPanel_nhapLayout = new javax.swing.GroupLayout(jPanel_nhap);
        jPanel_nhap.setLayout(jPanel_nhapLayout);
        jPanel_nhapLayout.setHorizontalGroup(
            jPanel_nhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quanly_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_nhapLayout.setVerticalGroup(
            jPanel_nhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nhapLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quanly_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_docgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_sach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_muontra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_nguoidung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel_logo))
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(close_form))
                    .addGroup(jPanel_menuLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jPanel_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_menuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_logo)
                .addGap(18, 18, 18)
                .addComponent(jPanel_docgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_sach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_muontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel_nguoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(close_form)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("QUẢN LÝ THƯ VIỆN");

        jPanel_view.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_view.setPreferredSize(new java.awt.Dimension(1070, 570));

        javax.swing.GroupLayout jPanel_viewLayout = new javax.swing.GroupLayout(jPanel_view);
        jPanel_view.setLayout(jPanel_viewLayout);
        jPanel_viewLayout.setHorizontalGroup(
            jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        jPanel_viewLayout.setVerticalGroup(
            jPanel_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_FrameLayout = new javax.swing.GroupLayout(jPanel_Frame);
        jPanel_Frame.setLayout(jPanel_FrameLayout);
        jPanel_FrameLayout.setHorizontalGroup(
            jPanel_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FrameLayout.createSequentialGroup()
                .addComponent(jPanel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(316, 316, 316))
                    .addComponent(jPanel_view, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)))
        );
        jPanel_FrameLayout.setVerticalGroup(
            jPanel_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FrameLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jPanel_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_formMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new form_main.DangNhap().setVisible(true);
    }//GEN-LAST:event_close_formMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_form;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JPanel jPanel_Frame;
    private javax.swing.JPanel jPanel_docgia;
    private javax.swing.JPanel jPanel_docgia1;
    private javax.swing.JPanel jPanel_docgia2;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_muontra;
    private javax.swing.JPanel jPanel_nguoidung;
    private javax.swing.JPanel jPanel_nhap;
    private javax.swing.JPanel jPanel_sach;
    private javax.swing.JPanel jPanel_thongke;
    private javax.swing.JPanel jPanel_view;
    private javax.swing.JLabel quanly_docgia;
    private javax.swing.JLabel quanly_docgia1;
    private javax.swing.JLabel quanly_docgia2;
    private javax.swing.JLabel quanly_muontra;
    private javax.swing.JLabel quanly_nguoidung;
    private javax.swing.JLabel quanly_nhap;
    private javax.swing.JLabel quanlysach;
    private javax.swing.JLabel thongke;
    // End of variables declaration//GEN-END:variables

   
     //To change body of generated methods, choose Tools | Templates.
    
                
}
